CREATE TABLE greeting_cards (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(200)  NOT NULL,
    category     VARCHAR(100)  NOT NULL,
    artist       VARCHAR(150)  NOT NULL,
    price        NUMERIC(8, 2) NOT NULL,
    stock_status VARCHAR(20)   NOT NULL
);

CREATE INDEX idx_greeting_cards_category ON greeting_cards (category);
CREATE INDEX idx_greeting_cards_title_lower ON greeting_cards (LOWER(title));
